<!--
 * @Author: liming
 * @Date: 2021-08-24 17:28:53
 * @LastEditTime: 2021-08-24 17:35:42
 * @FilePath: \01-尚硅谷李强\02-代码手敲\02-PromiseAPI\06-异常穿透现象是怎么回事.html
-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
          let p = new Promise((resolve, reject) =>{
          
            setTimeout(()=>{
                console.log('你好');
                resolve('OK')
                // 注意：只有成功之后才会执行接下来的回调函数
                // reject('error')
            },1000)
          
        })

     
        p.then(value => {
            console.log('我很好');
            // return new Promise((resolve, reject) => {
            //     console.log('小猫');
            //     resolve('success');
            // })
            throw('失败了')
        }).then(value => {
            console.log('小狗');
            console.log(value);
        }).then(value => {
            console.log('老虎');
            console.log(value);
        }).catch(reason=>{
            console.warn(reason);
            //我只要在最后指定一个失败的回调就可以了
            //其实用then方法也是可以的，不过用then方法需要传2个参数，用catch方法只需要传一个就行了
            //中间的那些环节都不需要指定失败的回调，这就是异常的穿透
        })
    </script>
</body>
</html>