<!--
 * @Author: liming
 * @Date: 2022-02-10 09:22:56
 * @LastEditTime: 2022-02-10 09:22:56
 * @FilePath: \04-async和await\0.html
-->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        /**
         * async定义的函数内部会默认返回一个promise对象，
         * 如果函数内部抛出异常或者是返回reject，都会使函数的promise状态为失败reject。
        */
        async function e() {
            throw new Error('has Error');
        }
        e().then(success => console.log('成功', success))
            .catch(error => console.log('失败', error));
        console.log('打印了')
    </script>
</body>

</html>